version: '3.1'
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: upt.2023
      MYSQL_DATABASE: db_accounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: upt.2023
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8484:8080
    depends_on:
      - db
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8585:8000"
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    restart: on-failure